### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by EvaKaul**
- updated overview page
- updates for using IIH Configurator
- new page "Usage.md"

### CODE REVIEW

**Comment by EvaKaul** [comment]
Hi Vladimir, maybe you could finally review this HowTo regarding Modbus TCP. Here I used the simulation tool (ModRSsim2) as Modbus Server, since we have no real Schneider PLC available.
Thanks in advance!

**Comment by vladEdge** [comment]
I am putting it on to-do list.

**Review by vladEdge — APPROVED** [review]
how-to is retested and described procedure is working. Approved.

**Comment by EvaKaul** [comment]
Thank's for the straightforward testing, Valadimir!

**Pull request merged**
